<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:decision="http://www.bonitasoft.org/ns/bpm/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/bpm/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/bpm/process">
  <process:MainProcess xmi:id="_Xo3VENWsEfCmFqYbmKWb-g" name="Project_Validation_Diagram_PINHEIRO" version="4.0" bonitaModelVersion="8">
    <elements xmi:type="process:Pool" xmi:id="_Xo3VEdWsEfCmFqYbmKWb-g" name="Project_Validation_Process_PINHEIRO" version="4.0">
      <elements xmi:type="process:Lane" xmi:id="_Xo3VEtWsEfCmFqYbmKWb-g" name="Employee lane" actor="_Xo3V59WsEfCmFqYbmKWb-g">
        <elements xmi:type="process:StartEvent" xmi:id="_Xo3VE9WsEfCmFqYbmKWb-g" name="Proposal Made" outgoing="_Xo3VstWsEfCmFqYbmKWb-g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Xo3VFNWsEfCmFqYbmKWb-g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Xo3VFdWsEfCmFqYbmKWb-g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Xo3VFtWsEfCmFqYbmKWb-g" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_Xo3VF9WsEfCmFqYbmKWb-g" name="Approve Proposal" outgoing="_Xo3VxNWsEfCmFqYbmKWb-g" incoming="_Xo3VstWsEfCmFqYbmKWb-g" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Xo3VGNWsEfCmFqYbmKWb-g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Xo3VGdWsEfCmFqYbmKWb-g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Xo3VGtWsEfCmFqYbmKWb-g" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_Xo3VG9WsEfCmFqYbmKWb-g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Xo3VHNWsEfCmFqYbmKWb-g" name="project" content="project" type="TYPE_VARIABLE" returnType="com.peproject.model.Project">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Xo3VHdWsEfCmFqYbmKWb-g" name="project" dataType="_Xo3WA9WsEfCmFqYbmKWb-g" className="com.peproject.model.Project"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Xo3VHtWsEfCmFqYbmKWb-g" name="proposalOK" content="proposalOK" type="TYPE_CONTRACT_INPUT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_Xo3VH9WsEfCmFqYbmKWb-g" name="proposalOK" type="BOOLEAN">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_Xo3VINWsEfCmFqYbmKWb-g"/>
              </referencedElements>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Xo3VIdWsEfCmFqYbmKWb-g" type="JAVA_METHOD" expression="setProposalOK">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Xo3VItWsEfCmFqYbmKWb-g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Xo3VI9WsEfCmFqYbmKWb-g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Xo3VJNWsEfCmFqYbmKWb-g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Xo3VJdWsEfCmFqYbmKWb-g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Xo3VJtWsEfCmFqYbmKWb-g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <BoundaryIntermediateEvents xmi:type="process:BoundaryTimerEvent" xmi:id="_Xo3VJ9WsEfCmFqYbmKWb-g" name="5 days" outgoing="_Xo3V3tWsEfCmFqYbmKWb-g">
            <condition xmi:type="expression:Expression" xmi:id="_Xo3VKNWsEfCmFqYbmKWb-g" name="5 Days 00:00:00" content="432000000L" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long"/>
          </BoundaryIntermediateEvents>
          <formMapping xmi:type="process:FormMapping" xmi:id="_Xo3VKdWsEfCmFqYbmKWb-g">
            <targetForm xmi:type="expression:Expression" xmi:id="_Xo3VKtWsEfCmFqYbmKWb-g" name="ApproveProposal" content="62a1ba69-8336-45e7-b318-4b2414ec2373" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_Xo3VK9WsEfCmFqYbmKWb-g">
            <inputs xmi:type="process:ContractInput" xmi:id="_Xo3VLNWsEfCmFqYbmKWb-g" name="proposalOK" type="BOOLEAN">
              <mapping xmi:type="process:ContractInputMapping" xmi:id="_Xo3VLdWsEfCmFqYbmKWb-g"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_Xo3VLtWsEfCmFqYbmKWb-g" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_Xo3VL9WsEfCmFqYbmKWb-g" name="Validate Project" outgoing="_Xo3V0dWsEfCmFqYbmKWb-g" incoming="_Xo3VuNWsEfCmFqYbmKWb-g" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Xo3VMNWsEfCmFqYbmKWb-g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Xo3VMdWsEfCmFqYbmKWb-g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Xo3VMtWsEfCmFqYbmKWb-g" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_Xo3VM9WsEfCmFqYbmKWb-g">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Xo3VNNWsEfCmFqYbmKWb-g" name="project" content="project" type="TYPE_VARIABLE" returnType="com.peproject.model.Project">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Xo3VNdWsEfCmFqYbmKWb-g" name="project" dataType="_Xo3WA9WsEfCmFqYbmKWb-g" className="com.peproject.model.Project"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Xo3VNtWsEfCmFqYbmKWb-g" name="projectOK" content="projectOK" type="TYPE_CONTRACT_INPUT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_Xo3VN9WsEfCmFqYbmKWb-g" name="projectOK" type="BOOLEAN">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_Xo3VONWsEfCmFqYbmKWb-g"/>
              </referencedElements>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Xo3VOdWsEfCmFqYbmKWb-g" type="JAVA_METHOD" expression="setProjectOK">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Xo3VOtWsEfCmFqYbmKWb-g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Xo3VO9WsEfCmFqYbmKWb-g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Xo3VPNWsEfCmFqYbmKWb-g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Xo3VPdWsEfCmFqYbmKWb-g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Xo3VPtWsEfCmFqYbmKWb-g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <BoundaryIntermediateEvents xmi:type="process:NonInterruptingBoundaryTimerEvent" xmi:id="_Xo3VP9WsEfCmFqYbmKWb-g" name="4 days" outgoing="_Xo3V4dWsEfCmFqYbmKWb-g">
            <condition xmi:type="expression:Expression" xmi:id="_Xo3VQNWsEfCmFqYbmKWb-g" name="4 Days 00:00:00" content="345600000L" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long"/>
          </BoundaryIntermediateEvents>
          <formMapping xmi:type="process:FormMapping" xmi:id="_Xo3VQdWsEfCmFqYbmKWb-g">
            <targetForm xmi:type="expression:Expression" xmi:id="_Xo3VQtWsEfCmFqYbmKWb-g" name="ValidateProject" content="56ff7085-df22-40c6-86a9-79031afcfdfd" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_Xo3VQ9WsEfCmFqYbmKWb-g">
            <inputs xmi:type="process:ContractInput" xmi:id="_Xo3VRNWsEfCmFqYbmKWb-g" name="projectOK" type="BOOLEAN">
              <mapping xmi:type="process:ContractInputMapping" xmi:id="_Xo3VRdWsEfCmFqYbmKWb-g"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_Xo3VRtWsEfCmFqYbmKWb-g" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_Xo3VR9WsEfCmFqYbmKWb-g" name="Do The Project" outgoing="_Xo3VvtWsEfCmFqYbmKWb-g" incoming="_Xo3Vu9WsEfCmFqYbmKWb-g" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Xo3VSNWsEfCmFqYbmKWb-g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Xo3VSdWsEfCmFqYbmKWb-g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Xo3VStWsEfCmFqYbmKWb-g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Xo3VS9WsEfCmFqYbmKWb-g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Xo3VTNWsEfCmFqYbmKWb-g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Xo3VTdWsEfCmFqYbmKWb-g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Xo3VTtWsEfCmFqYbmKWb-g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Xo3VT9WsEfCmFqYbmKWb-g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_Xo3VUNWsEfCmFqYbmKWb-g">
            <targetForm xmi:type="expression:Expression" xmi:id="_Xo3VUdWsEfCmFqYbmKWb-g" name="DoTheProject" content="35946db9-a6d6-4759-adbc-3d5b70cb6be5" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_Xo3VUtWsEfCmFqYbmKWb-g"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_Xo3VU9WsEfCmFqYbmKWb-g" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_Xo3VVNWsEfCmFqYbmKWb-g" name="Project Finished" incoming="_Xo3VwdWsEfCmFqYbmKWb-g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Xo3VVdWsEfCmFqYbmKWb-g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Xo3VVtWsEfCmFqYbmKWb-g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Xo3VV9WsEfCmFqYbmKWb-g" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_Xo3VWNWsEfCmFqYbmKWb-g" name="Proposal Refused" incoming="_Xo3VztWsEfCmFqYbmKWb-g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Xo3VWdWsEfCmFqYbmKWb-g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Xo3VWtWsEfCmFqYbmKWb-g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Xo3VW9WsEfCmFqYbmKWb-g" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_Xo3VXNWsEfCmFqYbmKWb-g" name="Project Refused" incoming="_Xo3V29WsEfCmFqYbmKWb-g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Xo3VXdWsEfCmFqYbmKWb-g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Xo3VXtWsEfCmFqYbmKWb-g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Xo3VX9WsEfCmFqYbmKWb-g" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_Xo3VYNWsEfCmFqYbmKWb-g" name="Proposal Approval?" outgoing="_Xo3Vx9WsEfCmFqYbmKWb-g _Xo3Vy9WsEfCmFqYbmKWb-g" incoming="_Xo3VxNWsEfCmFqYbmKWb-g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Xo3VYdWsEfCmFqYbmKWb-g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Xo3VYtWsEfCmFqYbmKWb-g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Xo3VY9WsEfCmFqYbmKWb-g" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_Xo3VZNWsEfCmFqYbmKWb-g" name="Project Approval?" outgoing="_Xo3V1NWsEfCmFqYbmKWb-g _Xo3V2NWsEfCmFqYbmKWb-g" incoming="_Xo3V0dWsEfCmFqYbmKWb-g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Xo3VZdWsEfCmFqYbmKWb-g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Xo3VZtWsEfCmFqYbmKWb-g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Xo3VZ9WsEfCmFqYbmKWb-g" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_Xo3VaNWsEfCmFqYbmKWb-g" name="Notify Proposal Approved" outgoing="_Xo3VtdWsEfCmFqYbmKWb-g" incoming="_Xo3Vx9WsEfCmFqYbmKWb-g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Xo3VadWsEfCmFqYbmKWb-g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Xo3VatWsEfCmFqYbmKWb-g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Xo3Va9WsEfCmFqYbmKWb-g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Xo3VbNWsEfCmFqYbmKWb-g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Xo3VbdWsEfCmFqYbmKWb-g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Xo3VbtWsEfCmFqYbmKWb-g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Xo3Vb9WsEfCmFqYbmKWb-g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Xo3VcNWsEfCmFqYbmKWb-g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_Xo3VcdWsEfCmFqYbmKWb-g" name="Analyze Impact" outgoing="_Xo3VuNWsEfCmFqYbmKWb-g" incoming="_Xo3VtdWsEfCmFqYbmKWb-g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Xo3VctWsEfCmFqYbmKWb-g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Xo3Vc9WsEfCmFqYbmKWb-g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Xo3VdNWsEfCmFqYbmKWb-g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Xo3VddWsEfCmFqYbmKWb-g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Xo3VdtWsEfCmFqYbmKWb-g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Xo3Vd9WsEfCmFqYbmKWb-g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Xo3VeNWsEfCmFqYbmKWb-g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Xo3VedWsEfCmFqYbmKWb-g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_Xo3VetWsEfCmFqYbmKWb-g" name="Notify Proposal Refusal" outgoing="_Xo3VztWsEfCmFqYbmKWb-g" incoming="_Xo3Vy9WsEfCmFqYbmKWb-g _Xo3V3tWsEfCmFqYbmKWb-g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Xo3Ve9WsEfCmFqYbmKWb-g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Xo3VfNWsEfCmFqYbmKWb-g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Xo3VfdWsEfCmFqYbmKWb-g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Xo3VftWsEfCmFqYbmKWb-g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Xo3Vf9WsEfCmFqYbmKWb-g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Xo3VgNWsEfCmFqYbmKWb-g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Xo3VgdWsEfCmFqYbmKWb-g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Xo3VgtWsEfCmFqYbmKWb-g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_Xo3Vg9WsEfCmFqYbmKWb-g" name="Notify Project Accepted" outgoing="_Xo3Vu9WsEfCmFqYbmKWb-g" incoming="_Xo3V1NWsEfCmFqYbmKWb-g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Xo3VhNWsEfCmFqYbmKWb-g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Xo3VhdWsEfCmFqYbmKWb-g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Xo3VhtWsEfCmFqYbmKWb-g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Xo3Vh9WsEfCmFqYbmKWb-g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Xo3ViNWsEfCmFqYbmKWb-g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Xo3VidWsEfCmFqYbmKWb-g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Xo3VitWsEfCmFqYbmKWb-g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Xo3Vi9WsEfCmFqYbmKWb-g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_Xo3VjNWsEfCmFqYbmKWb-g" name="Notify Project Refused" outgoing="_Xo3V29WsEfCmFqYbmKWb-g" incoming="_Xo3V2NWsEfCmFqYbmKWb-g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Xo3VjdWsEfCmFqYbmKWb-g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Xo3VjtWsEfCmFqYbmKWb-g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Xo3Vj9WsEfCmFqYbmKWb-g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Xo3VkNWsEfCmFqYbmKWb-g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Xo3VkdWsEfCmFqYbmKWb-g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Xo3VktWsEfCmFqYbmKWb-g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Xo3Vk9WsEfCmFqYbmKWb-g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Xo3VlNWsEfCmFqYbmKWb-g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_Xo3VldWsEfCmFqYbmKWb-g" name="Notify Project Delivery" outgoing="_Xo3VwdWsEfCmFqYbmKWb-g" incoming="_Xo3VvtWsEfCmFqYbmKWb-g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Xo3VltWsEfCmFqYbmKWb-g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Xo3Vl9WsEfCmFqYbmKWb-g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Xo3VmNWsEfCmFqYbmKWb-g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Xo3VmdWsEfCmFqYbmKWb-g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Xo3VmtWsEfCmFqYbmKWb-g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Xo3Vm9WsEfCmFqYbmKWb-g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Xo3VnNWsEfCmFqYbmKWb-g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Xo3VndWsEfCmFqYbmKWb-g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_Xo3VntWsEfCmFqYbmKWb-g" name="Notification Done" incoming="_Xo3V5NWsEfCmFqYbmKWb-g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Xo3Vn9WsEfCmFqYbmKWb-g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Xo3VoNWsEfCmFqYbmKWb-g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Xo3VodWsEfCmFqYbmKWb-g" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_Xo3VotWsEfCmFqYbmKWb-g" name="Notify Delay" outgoing="_Xo3V5NWsEfCmFqYbmKWb-g" incoming="_Xo3V4dWsEfCmFqYbmKWb-g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Xo3Vo9WsEfCmFqYbmKWb-g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Xo3VpNWsEfCmFqYbmKWb-g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Xo3VpdWsEfCmFqYbmKWb-g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Xo3VptWsEfCmFqYbmKWb-g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Xo3Vp9WsEfCmFqYbmKWb-g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Xo3VqNWsEfCmFqYbmKWb-g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Xo3VqdWsEfCmFqYbmKWb-g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Xo3VqtWsEfCmFqYbmKWb-g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_Y94AMNWsEfCmFqYbmKWb-g" name="Lane1"/>
      <elements xmi:type="process:Lane" xmi:id="_jlthkNWsEfCmFqYbmKWb-g" name="Lane2"/>
      <data xmi:type="process:BusinessObjectData" xmi:id="_Xo3Vq9WsEfCmFqYbmKWb-g" name="project" dataType="_Xo3WA9WsEfCmFqYbmKWb-g" className="com.peproject.model.Project">
        <defaultValue xmi:type="expression:Expression" xmi:id="_Xo3VrNWsEfCmFqYbmKWb-g" name="initProject()" content="def projectVar = new com.peproject.model.Project()&#xA;projectVar.proposal = projectInput?.proposal&#xA;return projectVar" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="com.peproject.model.Project">
          <referencedElements xmi:type="process:ContractInput" xmi:id="_Xo3VrdWsEfCmFqYbmKWb-g" name="projectInput" type="COMPLEX"/>
        </defaultValue>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_Xo3VrtWsEfCmFqYbmKWb-g">
        <targetForm xmi:type="expression:Expression" xmi:id="_Xo3Vr9WsEfCmFqYbmKWb-g" name="InitForm" content="422e3a3d-d7c4-4b05-9073-de7900e5ebf9" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_Xo3VsNWsEfCmFqYbmKWb-g">
        <targetForm xmi:type="expression:Expression" xmi:id="_Xo3VsdWsEfCmFqYbmKWb-g" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Xo3VstWsEfCmFqYbmKWb-g" target="_Xo3VF9WsEfCmFqYbmKWb-g" source="_Xo3VE9WsEfCmFqYbmKWb-g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Xo3Vs9WsEfCmFqYbmKWb-g"/>
        <condition xmi:type="expression:Expression" xmi:id="_Xo3VtNWsEfCmFqYbmKWb-g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Xo3VtdWsEfCmFqYbmKWb-g" target="_Xo3VcdWsEfCmFqYbmKWb-g" source="_Xo3VaNWsEfCmFqYbmKWb-g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Xo3VttWsEfCmFqYbmKWb-g"/>
        <condition xmi:type="expression:Expression" xmi:id="_Xo3Vt9WsEfCmFqYbmKWb-g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Xo3VuNWsEfCmFqYbmKWb-g" target="_Xo3VL9WsEfCmFqYbmKWb-g" source="_Xo3VcdWsEfCmFqYbmKWb-g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Xo3VudWsEfCmFqYbmKWb-g"/>
        <condition xmi:type="expression:Expression" xmi:id="_Xo3VutWsEfCmFqYbmKWb-g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Xo3Vu9WsEfCmFqYbmKWb-g" target="_Xo3VR9WsEfCmFqYbmKWb-g" source="_Xo3Vg9WsEfCmFqYbmKWb-g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Xo3VvNWsEfCmFqYbmKWb-g"/>
        <condition xmi:type="expression:Expression" xmi:id="_Xo3VvdWsEfCmFqYbmKWb-g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Xo3VvtWsEfCmFqYbmKWb-g" target="_Xo3VldWsEfCmFqYbmKWb-g" source="_Xo3VR9WsEfCmFqYbmKWb-g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Xo3Vv9WsEfCmFqYbmKWb-g"/>
        <condition xmi:type="expression:Expression" xmi:id="_Xo3VwNWsEfCmFqYbmKWb-g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Xo3VwdWsEfCmFqYbmKWb-g" target="_Xo3VVNWsEfCmFqYbmKWb-g" source="_Xo3VldWsEfCmFqYbmKWb-g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Xo3VwtWsEfCmFqYbmKWb-g"/>
        <condition xmi:type="expression:Expression" xmi:id="_Xo3Vw9WsEfCmFqYbmKWb-g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Xo3VxNWsEfCmFqYbmKWb-g" target="_Xo3VYNWsEfCmFqYbmKWb-g" source="_Xo3VF9WsEfCmFqYbmKWb-g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Xo3VxdWsEfCmFqYbmKWb-g"/>
        <condition xmi:type="expression:Expression" xmi:id="_Xo3VxtWsEfCmFqYbmKWb-g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Xo3Vx9WsEfCmFqYbmKWb-g" name="Yes" target="_Xo3VaNWsEfCmFqYbmKWb-g" source="_Xo3VYNWsEfCmFqYbmKWb-g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Xo3VyNWsEfCmFqYbmKWb-g"/>
        <condition xmi:type="expression:Expression" xmi:id="_Xo3VydWsEfCmFqYbmKWb-g" name="isProposalOK" content="project.proposalOK == true" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Xo3VytWsEfCmFqYbmKWb-g" name="project" dataType="_Xo3WA9WsEfCmFqYbmKWb-g" className="com.peproject.model.Project"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Xo3Vy9WsEfCmFqYbmKWb-g" name="No" target="_Xo3VetWsEfCmFqYbmKWb-g" source="_Xo3VYNWsEfCmFqYbmKWb-g" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Xo3VzNWsEfCmFqYbmKWb-g"/>
        <condition xmi:type="expression:Expression" xmi:id="_Xo3VzdWsEfCmFqYbmKWb-g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Xo3VztWsEfCmFqYbmKWb-g" target="_Xo3VWNWsEfCmFqYbmKWb-g" source="_Xo3VetWsEfCmFqYbmKWb-g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Xo3Vz9WsEfCmFqYbmKWb-g"/>
        <condition xmi:type="expression:Expression" xmi:id="_Xo3V0NWsEfCmFqYbmKWb-g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Xo3V0dWsEfCmFqYbmKWb-g" target="_Xo3VZNWsEfCmFqYbmKWb-g" source="_Xo3VL9WsEfCmFqYbmKWb-g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Xo3V0tWsEfCmFqYbmKWb-g"/>
        <condition xmi:type="expression:Expression" xmi:id="_Xo3V09WsEfCmFqYbmKWb-g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Xo3V1NWsEfCmFqYbmKWb-g" name="Yes" target="_Xo3Vg9WsEfCmFqYbmKWb-g" source="_Xo3VZNWsEfCmFqYbmKWb-g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Xo3V1dWsEfCmFqYbmKWb-g"/>
        <condition xmi:type="expression:Expression" xmi:id="_Xo3V1tWsEfCmFqYbmKWb-g" name="isProjectOK" content="project.projectOK == true" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Xo3V19WsEfCmFqYbmKWb-g" name="project" dataType="_Xo3WA9WsEfCmFqYbmKWb-g" className="com.peproject.model.Project"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Xo3V2NWsEfCmFqYbmKWb-g" name="No" target="_Xo3VjNWsEfCmFqYbmKWb-g" source="_Xo3VZNWsEfCmFqYbmKWb-g" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Xo3V2dWsEfCmFqYbmKWb-g"/>
        <condition xmi:type="expression:Expression" xmi:id="_Xo3V2tWsEfCmFqYbmKWb-g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Xo3V29WsEfCmFqYbmKWb-g" target="_Xo3VXNWsEfCmFqYbmKWb-g" source="_Xo3VjNWsEfCmFqYbmKWb-g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Xo3V3NWsEfCmFqYbmKWb-g"/>
        <condition xmi:type="expression:Expression" xmi:id="_Xo3V3dWsEfCmFqYbmKWb-g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Xo3V3tWsEfCmFqYbmKWb-g" target="_Xo3VetWsEfCmFqYbmKWb-g" source="_Xo3VJ9WsEfCmFqYbmKWb-g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Xo3V39WsEfCmFqYbmKWb-g"/>
        <condition xmi:type="expression:Expression" xmi:id="_Xo3V4NWsEfCmFqYbmKWb-g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Xo3V4dWsEfCmFqYbmKWb-g" target="_Xo3VotWsEfCmFqYbmKWb-g" source="_Xo3VP9WsEfCmFqYbmKWb-g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Xo3V4tWsEfCmFqYbmKWb-g"/>
        <condition xmi:type="expression:Expression" xmi:id="_Xo3V49WsEfCmFqYbmKWb-g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Xo3V5NWsEfCmFqYbmKWb-g" target="_Xo3VntWsEfCmFqYbmKWb-g" source="_Xo3VotWsEfCmFqYbmKWb-g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Xo3V5dWsEfCmFqYbmKWb-g"/>
        <condition xmi:type="expression:Expression" xmi:id="_Xo3V5tWsEfCmFqYbmKWb-g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_Xo3V59WsEfCmFqYbmKWb-g" documentation="This is an example of actor that is mapped to any ACME users" name="Employee actor" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_Xo3V6NWsEfCmFqYbmKWb-g">
        <inputs xmi:type="process:ContractInput" xmi:id="_Xo3V6dWsEfCmFqYbmKWb-g" name="projectInput" type="COMPLEX" dataReference="project">
          <inputs xmi:type="process:ContractInput" xmi:id="_Xo3V6tWsEfCmFqYbmKWb-g" name="proposal"/>
        </inputs>
        <constraints xmi:type="process:ContractConstraint" xmi:id="_Xo3V69WsEfCmFqYbmKWb-g" expression="projectInput?.proposal != null" errorMessage="proposal is mandatory for Project" name="mandatory_projectInput_proposal">
          <inputNames>projectInput</inputNames>
        </constraints>
      </contract>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Xo3V7NWsEfCmFqYbmKWb-g">
        <name xmi:type="expression:Expression" xmi:id="_Xo3V7dWsEfCmFqYbmKWb-g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Xo3V7tWsEfCmFqYbmKWb-g" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Xo3V79WsEfCmFqYbmKWb-g">
        <name xmi:type="expression:Expression" xmi:id="_Xo3V8NWsEfCmFqYbmKWb-g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Xo3V8dWsEfCmFqYbmKWb-g" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Xo3V8tWsEfCmFqYbmKWb-g">
        <name xmi:type="expression:Expression" xmi:id="_Xo3V89WsEfCmFqYbmKWb-g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Xo3V9NWsEfCmFqYbmKWb-g" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Xo3V9dWsEfCmFqYbmKWb-g">
        <name xmi:type="expression:Expression" xmi:id="_Xo3V9tWsEfCmFqYbmKWb-g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Xo3V99WsEfCmFqYbmKWb-g" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Xo3V-NWsEfCmFqYbmKWb-g">
        <name xmi:type="expression:Expression" xmi:id="_Xo3V-dWsEfCmFqYbmKWb-g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Xo3V-tWsEfCmFqYbmKWb-g" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_Xo3V-9WsEfCmFqYbmKWb-g" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_Xo3V_NWsEfCmFqYbmKWb-g" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_Xo3V_dWsEfCmFqYbmKWb-g" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_Xo3V_tWsEfCmFqYbmKWb-g" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_Xo3V_9WsEfCmFqYbmKWb-g" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_Xo3WANWsEfCmFqYbmKWb-g" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_Xo3WAdWsEfCmFqYbmKWb-g" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_Xo3WAtWsEfCmFqYbmKWb-g" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_Xo3WA9WsEfCmFqYbmKWb-g" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_Xo38INWsEfCmFqYbmKWb-g" type="Process" element="_Xo3VENWsEfCmFqYbmKWb-g" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_Xo38IdWsEfCmFqYbmKWb-g" type="2007" element="_Xo3VEdWsEfCmFqYbmKWb-g">
      <children xmi:type="notation:DecorationNode" xmi:id="_Xo38ItWsEfCmFqYbmKWb-g" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_Xo38I9WsEfCmFqYbmKWb-g" type="7001">
        <children xmi:type="notation:Node" xmi:id="_Xo38JNWsEfCmFqYbmKWb-g" type="3007" element="_Xo3VEtWsEfCmFqYbmKWb-g">
          <children xmi:type="notation:DecorationNode" xmi:id="_Xo38JdWsEfCmFqYbmKWb-g" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_Xo38JtWsEfCmFqYbmKWb-g" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_Xo38J9WsEfCmFqYbmKWb-g" type="3005" element="_Xo3VF9WsEfCmFqYbmKWb-g" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Xo38KNWsEfCmFqYbmKWb-g" type="5005"/>
              <children xmi:type="notation:Shape" xmi:id="_Xo38KdWsEfCmFqYbmKWb-g" type="3043" element="_Xo3VJ9WsEfCmFqYbmKWb-g" fontName=".AppleSystemUIFont">
                <children xmi:type="notation:DecorationNode" xmi:id="_Xo38KtWsEfCmFqYbmKWb-g" type="5055">
                  <layoutConstraint xmi:type="notation:Location" xmi:id="_Xo38K9WsEfCmFqYbmKWb-g" x="-27" y="-6"/>
                </children>
                <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Xo38LNWsEfCmFqYbmKWb-g"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Xo38LdWsEfCmFqYbmKWb-g" x="160" y="110"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Xo38LtWsEfCmFqYbmKWb-g" type="3002" element="_Xo3VE9WsEfCmFqYbmKWb-g" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_Xo38L9WsEfCmFqYbmKWb-g" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Xo38MNWsEfCmFqYbmKWb-g" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Xo38MdWsEfCmFqYbmKWb-g" x="60" y="118"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Xo38MtWsEfCmFqYbmKWb-g" type="3005" element="_Xo3VL9WsEfCmFqYbmKWb-g" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Xo38M9WsEfCmFqYbmKWb-g" type="5005"/>
              <children xmi:type="notation:Shape" xmi:id="_Xo38NNWsEfCmFqYbmKWb-g" type="3064" element="_Xo3VP9WsEfCmFqYbmKWb-g" fontName=".AppleSystemUIFont">
                <children xmi:type="notation:DecorationNode" xmi:id="_Xo38NdWsEfCmFqYbmKWb-g" type="5094">
                  <layoutConstraint xmi:type="notation:Location" xmi:id="_Xo38NtWsEfCmFqYbmKWb-g" x="-32" y="-6"/>
                </children>
                <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Xo38N9WsEfCmFqYbmKWb-g" x="6" y="42"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Xo38ONWsEfCmFqYbmKWb-g" x="701" y="110" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Xo38OdWsEfCmFqYbmKWb-g" type="3005" element="_Xo3VR9WsEfCmFqYbmKWb-g" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Xo38OtWsEfCmFqYbmKWb-g" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Xo38O9WsEfCmFqYbmKWb-g" x="1135" y="110" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Xo38PNWsEfCmFqYbmKWb-g" type="3003" element="_Xo3VVNWsEfCmFqYbmKWb-g" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_Xo38PdWsEfCmFqYbmKWb-g" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Xo38PtWsEfCmFqYbmKWb-g" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Xo38P9WsEfCmFqYbmKWb-g" x="1443" y="119"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Xo38QNWsEfCmFqYbmKWb-g" type="3003" element="_Xo3VWNWsEfCmFqYbmKWb-g" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_Xo38QdWsEfCmFqYbmKWb-g" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Xo38QtWsEfCmFqYbmKWb-g" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Xo38Q9WsEfCmFqYbmKWb-g" x="601" y="239" width="30" height="30"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Xo38RNWsEfCmFqYbmKWb-g" type="3003" element="_Xo3VXNWsEfCmFqYbmKWb-g" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_Xo38RdWsEfCmFqYbmKWb-g" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Xo38RtWsEfCmFqYbmKWb-g" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Xo38R9WsEfCmFqYbmKWb-g" x="1186" y="247"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Xo38SNWsEfCmFqYbmKWb-g" type="3008" element="_Xo3VYNWsEfCmFqYbmKWb-g" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_Xo38SdWsEfCmFqYbmKWb-g" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Xo38StWsEfCmFqYbmKWb-g" y="-58"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Xo38S9WsEfCmFqYbmKWb-g" x="309" y="115" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Xo38TNWsEfCmFqYbmKWb-g" type="3008" element="_Xo3VZNWsEfCmFqYbmKWb-g" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_Xo38TdWsEfCmFqYbmKWb-g" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Xo38TtWsEfCmFqYbmKWb-g" x="1" y="-58"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Xo38T9WsEfCmFqYbmKWb-g" x="860" y="116" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Xo38UNWsEfCmFqYbmKWb-g" type="3027" element="_Xo3VaNWsEfCmFqYbmKWb-g" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Xo38UdWsEfCmFqYbmKWb-g" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Xo38UtWsEfCmFqYbmKWb-g" x="407" y="104" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Xo38U9WsEfCmFqYbmKWb-g" type="3027" element="_Xo3VcdWsEfCmFqYbmKWb-g" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Xo38VNWsEfCmFqYbmKWb-g" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Xo38VdWsEfCmFqYbmKWb-g" x="560" y="110" width="100" height="49"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Xo38VtWsEfCmFqYbmKWb-g" type="3027" element="_Xo3VetWsEfCmFqYbmKWb-g" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Xo38V9WsEfCmFqYbmKWb-g" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Xo38WNWsEfCmFqYbmKWb-g" x="407" y="222" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Xo38WdWsEfCmFqYbmKWb-g" type="3027" element="_Xo3Vg9WsEfCmFqYbmKWb-g" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Xo38WtWsEfCmFqYbmKWb-g" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Xo38W9WsEfCmFqYbmKWb-g" x="980" y="106" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Xo38XNWsEfCmFqYbmKWb-g" type="3027" element="_Xo3VjNWsEfCmFqYbmKWb-g" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Xo38XdWsEfCmFqYbmKWb-g" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Xo38XtWsEfCmFqYbmKWb-g" x="987" y="228" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Xo38X9WsEfCmFqYbmKWb-g" type="3027" element="_Xo3VldWsEfCmFqYbmKWb-g" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Xo38YNWsEfCmFqYbmKWb-g" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Xo38YdWsEfCmFqYbmKWb-g" x="1260" y="104" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Xo38YtWsEfCmFqYbmKWb-g" type="3003" element="_Xo3VntWsEfCmFqYbmKWb-g" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_Xo38Y9WsEfCmFqYbmKWb-g" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Xo38ZNWsEfCmFqYbmKWb-g" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Xo38ZdWsEfCmFqYbmKWb-g" x="904" y="299"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Xo38ZtWsEfCmFqYbmKWb-g" type="3027" element="_Xo3VotWsEfCmFqYbmKWb-g" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Xo38Z9WsEfCmFqYbmKWb-g" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Xo38aNWsEfCmFqYbmKWb-g" x="757" y="287" width="100" height="50"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_Xo38adWsEfCmFqYbmKWb-g"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_Xo38atWsEfCmFqYbmKWb-g" fontName=".AppleSystemUIFont"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_Xo38a9WsEfCmFqYbmKWb-g"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_Xo38bNWsEfCmFqYbmKWb-g"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Xo38bdWsEfCmFqYbmKWb-g" x="19" y="10" width="1661" height="397"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_Y-ENcNWsEfCmFqYbmKWb-g" type="3007" element="_Y94AMNWsEfCmFqYbmKWb-g">
          <children xmi:type="notation:DecorationNode" xmi:id="_Y-GpsNWsEfCmFqYbmKWb-g" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_Y-GpsdWsEfCmFqYbmKWb-g" type="7002"/>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_Y-ENcdWsEfCmFqYbmKWb-g"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_Y-ENctWsEfCmFqYbmKWb-g" fontName=".AppleSystemUIFont"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_Y-ENc9WsEfCmFqYbmKWb-g"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_Y-GpstWsEfCmFqYbmKWb-g"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Y-ENdNWsEfCmFqYbmKWb-g" x="735" y="332"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_jmFVANWsEfCmFqYbmKWb-g" type="3007" element="_jlthkNWsEfCmFqYbmKWb-g">
          <children xmi:type="notation:DecorationNode" xmi:id="_jmHxQNWsEfCmFqYbmKWb-g" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_jmIYUNWsEfCmFqYbmKWb-g" type="7002"/>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_jmFVAdWsEfCmFqYbmKWb-g"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_jmFVAtWsEfCmFqYbmKWb-g" fontName=".AppleSystemUIFont"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_jmFVA9WsEfCmFqYbmKWb-g"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_jmIYUdWsEfCmFqYbmKWb-g"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_jmFVBNWsEfCmFqYbmKWb-g" x="960" y="726"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_Xo38btWsEfCmFqYbmKWb-g"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_Xo38b9WsEfCmFqYbmKWb-g" fontName=".AppleSystemUIFont"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_Xo38cNWsEfCmFqYbmKWb-g"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_Xo38cdWsEfCmFqYbmKWb-g"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Xo38ctWsEfCmFqYbmKWb-g" width="1680" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_Xo38c9WsEfCmFqYbmKWb-g"/>
    <edges xmi:type="notation:Connector" xmi:id="_Xo38dNWsEfCmFqYbmKWb-g" type="4001" element="_Xo3VstWsEfCmFqYbmKWb-g" source="_Xo38LtWsEfCmFqYbmKWb-g" target="_Xo38J9WsEfCmFqYbmKWb-g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Xo38ddWsEfCmFqYbmKWb-g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Xo38dtWsEfCmFqYbmKWb-g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Xo38d9WsEfCmFqYbmKWb-g" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Xo38eNWsEfCmFqYbmKWb-g" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Xo38edWsEfCmFqYbmKWb-g" type="4001" element="_Xo3VtdWsEfCmFqYbmKWb-g" source="_Xo38UNWsEfCmFqYbmKWb-g" target="_Xo38U9WsEfCmFqYbmKWb-g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Xo38etWsEfCmFqYbmKWb-g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Xo38e9WsEfCmFqYbmKWb-g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Xo38fNWsEfCmFqYbmKWb-g" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Xo38fdWsEfCmFqYbmKWb-g" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Xo38ftWsEfCmFqYbmKWb-g" type="4001" element="_Xo3VuNWsEfCmFqYbmKWb-g" source="_Xo38U9WsEfCmFqYbmKWb-g" target="_Xo38MtWsEfCmFqYbmKWb-g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Xo38f9WsEfCmFqYbmKWb-g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Xo38gNWsEfCmFqYbmKWb-g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Xo38gdWsEfCmFqYbmKWb-g" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Xo38gtWsEfCmFqYbmKWb-g" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Xo38g9WsEfCmFqYbmKWb-g" type="4001" element="_Xo3Vu9WsEfCmFqYbmKWb-g" source="_Xo38WdWsEfCmFqYbmKWb-g" target="_Xo38OdWsEfCmFqYbmKWb-g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Xo38hNWsEfCmFqYbmKWb-g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Xo38hdWsEfCmFqYbmKWb-g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Xo38htWsEfCmFqYbmKWb-g" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Xo38h9WsEfCmFqYbmKWb-g" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Xo38iNWsEfCmFqYbmKWb-g" type="4001" element="_Xo3VvtWsEfCmFqYbmKWb-g" source="_Xo38OdWsEfCmFqYbmKWb-g" target="_Xo38X9WsEfCmFqYbmKWb-g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Xo38idWsEfCmFqYbmKWb-g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Xo38itWsEfCmFqYbmKWb-g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Xo38i9WsEfCmFqYbmKWb-g" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Xo38jNWsEfCmFqYbmKWb-g" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Xo38jdWsEfCmFqYbmKWb-g" type="4001" element="_Xo3VwdWsEfCmFqYbmKWb-g" source="_Xo38X9WsEfCmFqYbmKWb-g" target="_Xo38PNWsEfCmFqYbmKWb-g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Xo38jtWsEfCmFqYbmKWb-g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Xo38j9WsEfCmFqYbmKWb-g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Xo38kNWsEfCmFqYbmKWb-g" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Xo38kdWsEfCmFqYbmKWb-g" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Xo38ktWsEfCmFqYbmKWb-g" type="4001" element="_Xo3VxNWsEfCmFqYbmKWb-g" source="_Xo38J9WsEfCmFqYbmKWb-g" target="_Xo38SNWsEfCmFqYbmKWb-g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Xo38k9WsEfCmFqYbmKWb-g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Xo38lNWsEfCmFqYbmKWb-g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Xo38ldWsEfCmFqYbmKWb-g" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Xo38ltWsEfCmFqYbmKWb-g" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Xo38l9WsEfCmFqYbmKWb-g" type="4001" element="_Xo3Vx9WsEfCmFqYbmKWb-g" source="_Xo38SNWsEfCmFqYbmKWb-g" target="_Xo38UNWsEfCmFqYbmKWb-g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Xo38mNWsEfCmFqYbmKWb-g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Xo38mdWsEfCmFqYbmKWb-g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Xo38mtWsEfCmFqYbmKWb-g" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Xo38m9WsEfCmFqYbmKWb-g" points="[-1, -3, -76, 0]$[55, -2, -20, 1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Xo38nNWsEfCmFqYbmKWb-g" id="(1.0,0.5813953488372093)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Xo38ndWsEfCmFqYbmKWb-g" id="(0.16666666666666666,0.5333333333333333)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Xo38ntWsEfCmFqYbmKWb-g" type="4001" element="_Xo3Vy9WsEfCmFqYbmKWb-g" source="_Xo38SNWsEfCmFqYbmKWb-g" target="_Xo38VtWsEfCmFqYbmKWb-g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Xo38n9WsEfCmFqYbmKWb-g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Xo38oNWsEfCmFqYbmKWb-g" x="-25" y="-15"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Xo38odWsEfCmFqYbmKWb-g" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Xo38otWsEfCmFqYbmKWb-g" points="[0, 22, -137, -89]$[0, 111, -137, 0]$[87, 111, -50, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Xo38o9WsEfCmFqYbmKWb-g" type="4001" element="_Xo3VztWsEfCmFqYbmKWb-g" source="_Xo38VtWsEfCmFqYbmKWb-g" target="_Xo38QNWsEfCmFqYbmKWb-g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Xo38pNWsEfCmFqYbmKWb-g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Xo38pdWsEfCmFqYbmKWb-g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Xo38ptWsEfCmFqYbmKWb-g" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Xo38p9WsEfCmFqYbmKWb-g" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Xo38qNWsEfCmFqYbmKWb-g" type="4001" element="_Xo3V0dWsEfCmFqYbmKWb-g" source="_Xo38MtWsEfCmFqYbmKWb-g" target="_Xo38TNWsEfCmFqYbmKWb-g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Xo38qdWsEfCmFqYbmKWb-g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Xo38qtWsEfCmFqYbmKWb-g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Xo38q9WsEfCmFqYbmKWb-g" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Xo38rNWsEfCmFqYbmKWb-g" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Xo38rdWsEfCmFqYbmKWb-g" type="4001" element="_Xo3V1NWsEfCmFqYbmKWb-g" source="_Xo38TNWsEfCmFqYbmKWb-g" target="_Xo38WdWsEfCmFqYbmKWb-g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Xo38rtWsEfCmFqYbmKWb-g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Xo38r9WsEfCmFqYbmKWb-g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Xo38sNWsEfCmFqYbmKWb-g" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Xo38sdWsEfCmFqYbmKWb-g" points="[-2, -8, -92, 0]$[78, -8, -12, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Xo38stWsEfCmFqYbmKWb-g" id="(1.0,0.6511627906976745)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Xo38s9WsEfCmFqYbmKWb-g" id="(0.1,0.5)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Xo38tNWsEfCmFqYbmKWb-g" type="4001" element="_Xo3V2NWsEfCmFqYbmKWb-g" source="_Xo38TNWsEfCmFqYbmKWb-g" target="_Xo38XNWsEfCmFqYbmKWb-g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Xo38tdWsEfCmFqYbmKWb-g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Xo38ttWsEfCmFqYbmKWb-g" x="-38" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Xo38t9WsEfCmFqYbmKWb-g" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Xo38uNWsEfCmFqYbmKWb-g" points="[0, 22, -156, -95]$[0, 116, -156, -1]$[106, 116, -50, -1]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Xo38udWsEfCmFqYbmKWb-g" type="4001" element="_Xo3V29WsEfCmFqYbmKWb-g" source="_Xo38XNWsEfCmFqYbmKWb-g" target="_Xo38RNWsEfCmFqYbmKWb-g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Xo38utWsEfCmFqYbmKWb-g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Xo38u9WsEfCmFqYbmKWb-g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Xo38vNWsEfCmFqYbmKWb-g" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Xo38vdWsEfCmFqYbmKWb-g" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Xo38vtWsEfCmFqYbmKWb-g" type="4001" element="_Xo3V3tWsEfCmFqYbmKWb-g" source="_Xo38KdWsEfCmFqYbmKWb-g" target="_Xo38VtWsEfCmFqYbmKWb-g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Xo38v9WsEfCmFqYbmKWb-g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Xo38wNWsEfCmFqYbmKWb-g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Xo38wdWsEfCmFqYbmKWb-g" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Xo38wtWsEfCmFqYbmKWb-g" points="[-12, 0, -237, -96]$[-12, 84, -237, -12]$[206, 84, -19, -12]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Xo38w9WsEfCmFqYbmKWb-g" id="(1.0,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Xo38xNWsEfCmFqYbmKWb-g" id="(0.15833333333333333,0.85)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Xo38xdWsEfCmFqYbmKWb-g" type="4001" element="_Xo3V4dWsEfCmFqYbmKWb-g" source="_Xo38NNWsEfCmFqYbmKWb-g" target="_Xo38ZtWsEfCmFqYbmKWb-g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Xo38xtWsEfCmFqYbmKWb-g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Xo38x9WsEfCmFqYbmKWb-g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Xo38yNWsEfCmFqYbmKWb-g" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Xo38ydWsEfCmFqYbmKWb-g" points="[-7, 13, -37, -81]$[-7, 91, -37, -3]$[29, 91, -1, -3]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Xo38ytWsEfCmFqYbmKWb-g" id="(0.01,0.5)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Xo38y9WsEfCmFqYbmKWb-g" type="4001" element="_Xo3V5NWsEfCmFqYbmKWb-g" source="_Xo38ZtWsEfCmFqYbmKWb-g" target="_Xo38YtWsEfCmFqYbmKWb-g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Xo38zNWsEfCmFqYbmKWb-g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Xo38zdWsEfCmFqYbmKWb-g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Xo38ztWsEfCmFqYbmKWb-g" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Xo38z9WsEfCmFqYbmKWb-g" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
